---
title: "StaticVersionFinalProject"
author: "Alyssa Bigness"
date: "3/23/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readxl)
library(shiny)


mlbsalary_df <- read_xlsx(path = "data/MLBPlayerSalaries.xlsx")

mlbsalary_late80s <- 
  mlbsalary_df %>%
  filter(.,
         Year == "1988" | Year == "1989") %>%
  mutate(.,
         Player = fct_reorder(Player, Salary)) %>%
  filter(.,
         Team == "Los Angeles Angels")

ggplot(data = mlbsalary_late80s,
           aes(x = Player,
               y = Salary)) + geom_col() + coord_flip()
  



```

```{r}
mlbsalary_df <- read_xlsx(path = "data/MLBPlayerSalaries.xlsx")

library(tidyverse)
test_df <- tibble(position_type = c("A", "A", "B", "B", "C", "D", "A"))
test_df %>% group_by(position_type) %>%
  summarise(nplayers = n())

# problem fixed
mlbsalary_88 <- 
  mlbsalary_df %>%
  filter(.,
         Year == "1988",
         Team == "Los Angeles Angels") %>%
  group_by(Position) %>%
  summarize(.,
            nPlayers = n()) %>%
  mutate(.,
         Position = fct_reorder(Position, nPlayers)) 

ggplot(data = mlbsalary_88,
           aes(x = Position, y = nPlayers)) + geom_bar(color = "black", fill = "white", stat = "identity") + 
      coord_flip() + ylab("Number of Players") + 
  
```


```{r}
mlbsalary_sub <-
    mlb_df %>% filter(.,
                      Year == "1988",
                      Team == "Boston Red Sox" |
                        Team == "Los Angeles Angels" |
                        Team == "New York Yankees") %>%
      mutate(.,
             Player = fct_reorder(Player, Salary),
             Salary = Salary/1000000) %>%
      slice(1:35)

ggplot(data = mlbsalary_sub,
           aes(x = Player,
               y = Salary)) + geom_col(aes(fill = Team), color = "black") + 
      geom_hline(aes(yintercept = mean(Salary)), color = "black", linetype = 2, size = 1.25) + coord_flip() + 
      ylab("Salary per Million") + theme_bw()
```


```{r}
library(RColorBrewer)
mlbpositions_sub <-
    mlb_df %>% filter(.,
                      Year == "2011",
                      Team == "Boston Red Sox" | Team == "New York Yankees" | Team == "Los Angeles Angels") %>%
      group_by(Team, Position) %>%
      summarize(.,
                nPlayers = n())

ggplot(data = mlbpositions_sub,
           aes(x = fct_reorder(Position, nPlayers), y = nPlayers)) + geom_bar(aes(fill = Team), color = "black", stat = "identity", position = "dodge") + 
      coord_flip() + ylab("Number of Players") + xlab("Positions") +
  scale_fill_brewer(palette = "Set2")
```




things to do 
- change axis labels
- fix slicing problem
- fix theme input


